// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: microservices/mail/gen_files/mail.proto

// export PATH="$PATH:$(go env GOPATH)/bin"
// go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latests
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --experimental_allow_proto3_optional --go-grpc_opt=paths=source_relative microservices/mail/gen_files/mail.proto

package mail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Username    string  `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Useremail   string  `protobuf:"bytes,3,opt,name=useremail,proto3" json:"useremail,omitempty"`
	Promocode   *string `protobuf:"bytes,4,opt,name=promocode,proto3,oneof" json:"promocode,omitempty"`
	OrderStatus *string `protobuf:"bytes,5,opt,name=orderStatus,proto3,oneof" json:"orderStatus,omitempty"`
	OrderID     *int32  `protobuf:"varint,6,opt,name=orderID,proto3,oneof" json:"orderID,omitempty"`
}

func (x *Mail) Reset() {
	*x = Mail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_mail_gen_files_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_mail_gen_files_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_microservices_mail_gen_files_mail_proto_rawDescGZIP(), []int{0}
}

func (x *Mail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Mail) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Mail) GetUseremail() string {
	if x != nil {
		return x.Useremail
	}
	return ""
}

func (x *Mail) GetPromocode() string {
	if x != nil && x.Promocode != nil {
		return *x.Promocode
	}
	return ""
}

func (x *Mail) GetOrderStatus() string {
	if x != nil && x.OrderStatus != nil {
		return *x.OrderStatus
	}
	return ""
}

func (x *Mail) GetOrderID() int32 {
	if x != nil && x.OrderID != nil {
		return *x.OrderID
	}
	return 0
}

type Nothing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccessful bool `protobuf:"varint,1,opt,name=isSuccessful,proto3" json:"isSuccessful,omitempty"`
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_mail_gen_files_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_mail_gen_files_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_microservices_mail_gen_files_mail_proto_rawDescGZIP(), []int{1}
}

func (x *Nothing) GetIsSuccessful() bool {
	if x != nil {
		return x.IsSuccessful
	}
	return false
}

var File_microservices_mail_gen_files_mail_proto protoreflect.FileDescriptor

var file_microservices_mail_gen_files_mail_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x6d,
	0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0xe7, 0x01, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x6d, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01,
	0x12, 0x1d, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x02, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x88, 0x01, 0x01, 0x42,
	0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x0e, 0x0a,
	0x0c, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2d, 0x0a, 0x07, 0x4e, 0x6f, 0x74,
	0x68, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x32, 0x36, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x61, 0x69, 0x6c, 0x12, 0x0a, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x1a,
	0x0d, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x00,
	0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_microservices_mail_gen_files_mail_proto_rawDescOnce sync.Once
	file_microservices_mail_gen_files_mail_proto_rawDescData = file_microservices_mail_gen_files_mail_proto_rawDesc
)

func file_microservices_mail_gen_files_mail_proto_rawDescGZIP() []byte {
	file_microservices_mail_gen_files_mail_proto_rawDescOnce.Do(func() {
		file_microservices_mail_gen_files_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_microservices_mail_gen_files_mail_proto_rawDescData)
	})
	return file_microservices_mail_gen_files_mail_proto_rawDescData
}

var file_microservices_mail_gen_files_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_microservices_mail_gen_files_mail_proto_goTypes = []interface{}{
	(*Mail)(nil),    // 0: mail.Mail
	(*Nothing)(nil), // 1: mail.Nothing
}
var file_microservices_mail_gen_files_mail_proto_depIdxs = []int32{
	0, // 0: mail.MailService.SendMail:input_type -> mail.Mail
	1, // 1: mail.MailService.SendMail:output_type -> mail.Nothing
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_microservices_mail_gen_files_mail_proto_init() }
func file_microservices_mail_gen_files_mail_proto_init() {
	if File_microservices_mail_gen_files_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microservices_mail_gen_files_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_mail_gen_files_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nothing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_microservices_mail_gen_files_mail_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microservices_mail_gen_files_mail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_microservices_mail_gen_files_mail_proto_goTypes,
		DependencyIndexes: file_microservices_mail_gen_files_mail_proto_depIdxs,
		MessageInfos:      file_microservices_mail_gen_files_mail_proto_msgTypes,
	}.Build()
	File_microservices_mail_gen_files_mail_proto = out.File
	file_microservices_mail_gen_files_mail_proto_rawDesc = nil
	file_microservices_mail_gen_files_mail_proto_goTypes = nil
	file_microservices_mail_gen_files_mail_proto_depIdxs = nil
}
