version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    networks:
      - mynet
    ports:
      - '${TEST_DB_PORT}:5432'
    volumes:
      - './_postgres:/docker-entrypoint'
      - 'dbData:/var/lib/postgresql/data'
  
  app:
    container_name: go
    environment:
      - TEST_POSTGRES_USER=${TEST_DB_USER}
      - TEST_POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_POSTGRES_DB=${TEST_DB_NAME}
      - TEST_DATABASE_HOST=${TEST_DB_HOST}
      - TEST_DATABASE_PORT=${TEST_DB_PORT}
    build:
      context: .
    ports:
      - 8080:8080
    restart: on-failure
    links:
      - postgres:postgres
    volumes:
      - .:/app
    depends_on:
      - "postgres"
    networks:
      - mynet

volumes:
  dbData:


networks:
  mynet:
    driver: bridge