FROM golang:alpine
LABEL maintainer="Base"
WORKDIR /auth
COPY . .
RUN go install github.com/githubnemo/CompileDaemon@latest
RUN apk update && apk add bash
CMD /bin/bash -c '$GOPATH/bin/CompileDaemon -log-prefix=false -polling=true -polling-interval=500 -build="go build ./microservices/auth/" -command="./auth"'
EXPOSE 8082
