FROM golang:alpine
LABEL maintainer="Base"
WORKDIR /mail
COPY . .
RUN go install github.com/githubnemo/CompileDaemon@latest
RUN apk update && apk add bash
EXPOSE 8084
CMD /bin/bash -c '$GOPATH/bin/CompileDaemon -log-prefix=false -polling=true -polling-interval=500 -build="go build ./microservices/mail/" -command="./mail"'
