version: "3.1"

services:
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - "9100:9100"
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    networks:
      - mynet
    ports:
      - '${TEST_DB_PORT}:${TEST_DB_PORT}'
    volumes:
      - './_postgres:/docker-entrypoint'
      - 'dbData:/var/lib/postgresql/data'

  session:
    build:
      context: .
      dockerfile: ./Dockerfile-session
    container_name: auth
    ports:
      - "8082:8082"
    expose:
      - "8082"
    volumes:
      - ./:/auth
    restart: on-failure
    networks:
      - mynet
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082" ]
      interval: 30s
      timeout: 10s
      retries: 5

  orders:
    build:
      context: .
      dockerfile: ./Dockerfile-orders
    container_name: orders
    ports:
      - "8083:8083"
    expose:
      - "8083"
    environment:
      - DB_PORT=${DB_PORT}
      - TEST_POSTGRES_USER=${TEST_DB_USER}
      - TEST_POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_POSTGRES_DB=${TEST_DB_NAME}
      - TEST_DATABASE_HOST=${TEST_DB_HOST}
      - TEST_DATABASE_PORT=${TEST_DB_PORT}
    volumes:
      - ./:/orders
    restart: on-failure
    depends_on:
      - postgres
      - session
    networks:
      - mynet
    links:
      - postgres:postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    container_name: go
    environment:
      - DB_PORT=${DB_PORT}
      - TEST_POSTGRES_USER=${TEST_DB_USER}
      - TEST_POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_POSTGRES_DB=${TEST_DB_NAME}
      - TEST_DATABASE_HOST=${TEST_DB_HOST}
      - TEST_DATABASE_PORT=${TEST_DB_PORT}
    build:
      context: .
    ports:
      - 8080:8080
    restart: on-failure
    links:
      - postgres:postgres
    volumes:
      - ./:/app
      - /home/ubuntu/front-next/dist/img:/avatars
    depends_on:
      - "postgres"
      - "session"
      - "orders"
    networks:
      - mynet

volumes:
  grafana-storage:
  prometheus_data:
  .:
    external: true
  dbData:


networks:
  mynet:
    driver: bridge
