global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'go:8080' ]

  - job_name: 'session microservice'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'auth:8082' ]

  - job_name: 'orders microservice'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'orders:8083' ]

  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node-exporter:9100' ]