DROP TABLE IF EXISTS "orders" CASCADE;

DROP TABLE IF EXISTS "orderItems" CASCADE;

DROP TABLE IF EXISTS "products" CASCADE;

DROP TABLE IF EXISTS "adress" CASCADE;

DROP TABLE IF EXISTS "payment" CASCADE;

DROP TABLE IF EXISTS "users" CASCADE;