DROP TABLE IF EXISTS "typesOfItems" CASCADE;

DROP TABLE IF EXISTS "items" CASCADE;

DROP TABLE IF EXISTS "paymentsOfUsers" CASCADE;

DROP TABLE IF EXISTS "addressesOfUsers" CASCADE;

DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "ratingOfItems";

DROP TABLE IF EXISTS "vendors" CASCADE;

DROP TABLE IF EXISTS "stockOfItems";

DROP TABLE IF EXISTS "orders" CASCADE;

DROP TABLE IF EXISTS "orderItem";

DROP TABLE IF EXISTS "admins";

DROP TYPE IF EXISTS "AdminPermissions";

DROP TYPE IF EXISTS "OrderStatus";

DROP TYPE IF EXISTS "PaymentStatus";

DROP TYPE IF EXISTS "TypesOfPayment";