DROP TABLE IF EXISTS "comments" CASCADE;

DROP TABLE IF EXISTS "orders" CASCADE;

DROP TABLE IF EXISTS "orderitems" CASCADE;

DROP TABLE IF EXISTS "products" CASCADE;

DROP TABLE IF EXISTS "address" CASCADE;

DROP TABLE IF EXISTS "payment" CASCADE;

DROP TABLE IF EXISTS "users" CASCADE;