basePath: /api/v1
definitions:
  model.Address:
    properties:
      city:
        type: string
      house:
        type: string
      id:
        type: integer
      priority:
        type: boolean
      street:
        type: string
    type: object
  model.Error:
    properties:
      error: {}
    type: object
  model.MakeOrder:
    properties:
      address:
        type: integer
      card:
        type: integer
      deliveryDate:
        type: string
      items:
        items:
          type: integer
        type: array
      userid:
        type: integer
    type: object
  model.Order:
    properties:
      address:
        type: integer
      card:
        type: integer
      creationDate:
        type: string
      deliveryDate:
        type: string
      id:
        type: integer
      items:
        items:
          $ref: '#/definitions/model.OrderItem'
        type: array
      orderstatus:
        type: string
      paymentstatus:
        type: string
      userid:
        type: integer
    type: object
  model.OrderItem:
    properties:
      count:
        type: integer
      item:
        $ref: '#/definitions/model.Product'
    type: object
  model.PaymentMethod:
    properties:
      expirydate:
        type: string
      id:
        type: integer
      number:
        type: string
      priority:
        type: boolean
      type:
        type: string
    type: object
  model.Product:
    properties:
      category:
        type: string
      id:
        type: integer
      imgsrc:
        type: string
      lowprice:
        type: number
      name:
        type: string
      price:
        type: number
      rating:
        type: number
    type: object
  model.ProductCart:
    properties:
      items:
        items:
          type: integer
        type: array
    type: object
  model.ProductCartItem:
    properties:
      itemid:
        type: integer
    type: object
  model.Response:
    properties:
      body: {}
    type: object
  model.UserCreateParams:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  model.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.UserProfile:
    properties:
      address:
        items:
          $ref: '#/definitions/model.Address'
        type: array
      avatar:
        type: string
      email:
        type: string
      paymentmethods:
        items:
          $ref: '#/definitions/model.PaymentMethod'
        type: array
      phone:
        type: string
      username:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Reazon back server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Reozon API
  version: "1.0"
paths:
  /cart:
    get:
      consumes:
      - application/json
      description: gets user's cart
      operationId: GetCart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Order'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: gets user's cart
      tags:
      - Order
    post:
      consumes:
      - application/json
      description: updates user's cart
      operationId: UpdateCart
      parameters:
      - description: ProductCart items
        in: body
        name: items
        required: true
        schema:
          $ref: '#/definitions/model.ProductCart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: updates user's cart
      tags:
      - Order
  /cart/deletefromcart:
    post:
      consumes:
      - application/json
      description: Deletes Item From cart
      operationId: DeleteItemFromCart
      parameters:
      - description: ProductCart item
        in: body
        name: items
        required: true
        schema:
          $ref: '#/definitions/model.ProductCartItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "404":
          description: Not found - Requested entity is not found in database
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Deletes Item From cart
      tags:
      - Order
  /cart/insertintocart:
    post:
      consumes:
      - application/json
      description: Adds item to cart
      operationId: AddItemToCart
      parameters:
      - description: ProductCart item
        in: body
        name: items
        required: true
        schema:
          $ref: '#/definitions/model.ProductCartItem'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Adds item to cart
      tags:
      - Order
  /cart/makeorder:
    post:
      consumes:
      - application/json
      description: makes user's order
      operationId: MakeOrder
      parameters:
      - description: MakeOrder params
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/model.MakeOrder'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: makes user's order
      tags:
      - Order
  /cart/orders:
    get:
      consumes:
      - application/json
      description: gets user's orders
      operationId: GetOrder
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Order'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: gets user's orders
      tags:
      - Order
  /login:
    post:
      consumes:
      - application/json
      description: Log in user
      operationId: login
      parameters:
      - description: UserDB params
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserLogin'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Logs in and returns the authentication  cookie
      tags:
      - User
  /logout:
    delete:
      consumes:
      - application/json
      description: Logs out user
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
      summary: Logs out user
      tags:
      - User
  /products:
    get:
      consumes:
      - application/json
      description: Gets products for main page
      operationId: getMain
      parameters:
      - description: lastitemid
        in: query
        name: lastitemid
        required: true
        type: string
      - description: count
        in: query
        name: count
        required: true
        type: string
      - description: sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Gets products for main page
      tags:
      - Products
  /products/{category}:
    get:
      consumes:
      - application/json
      description: Gets products by category
      operationId: GetProductsByCategory
      parameters:
      - description: The category of products
        in: path
        name: category
        required: true
        type: string
      - description: lastitemid
        in: query
        name: lastitemid
        required: true
        type: string
      - description: count
        in: query
        name: count
        required: true
        type: string
      - description: sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Gets products by category
      tags:
      - Products
  /session:
    get:
      consumes:
      - application/json
      description: Checks if user has active session
      operationId: session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
      summary: Checks if user has active session
      tags:
      - User
  /signup:
    post:
      consumes:
      - application/json
      description: Sign up user
      operationId: signup
      parameters:
      - description: UserDB params
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserCreateParams'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "409":
          description: Conflict - UserDB already exists
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Signs up and returns the authentication  cookie
      tags:
      - User
  /user/avatar:
    post:
      consumes:
      - multipart/form-data
      description: sets user's avatar
      operationId: setAvatar
      parameters:
      - description: user's avatar
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Set user's avatar
      tags:
      - User
  /user/profile:
    get:
      consumes:
      - application/json
      description: gets user by username in cookies
      operationId: getUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserProfile'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Get current user
      tags:
      - User
    post:
      consumes:
      - application/json
      description: changes user parameters
      operationId: changeUserParameters
      parameters:
      - description: UserProfile params
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "401":
          description: Unauthorized - Access token is missing or invalid
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: changes user parameters
      tags:
      - User
swagger: "2.0"
